name: Python application

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Install dependencies
        run: uv sync

      - name: Build WxDatDecryptApp with Nuitka
        uses: Nuitka/Nuitka-Action@v1.4
        with:
          script-name: app.py
          mode: onefile
          output-dir: dist
          output-file: WxDatDecryptApp.exe
          include-data-dir: |
            frontend/templates=frontend/templates
            frontend/static=frontend/static
          include-data-files: |
            backend/src/wxam/VoipEngine.dll=backend/src/wxam/VoipEngine.dll
          windows-icon-from-ico: frontend/static/icons/app.ico
          windows-console-mode: disable
          disable-cache: false
          assume-yes-for-downloads: true

          lto: yes
          jobs: -1

          noinclude-setuptools-mode: error
          noinclude-pytest-mode: error
          noinclude-unittest-mode: nofollow
          noinclude-pydoc-mode: error
          noinclude-IPython-mode: error

          python-flag: no_docstrings,no_asserts

          show-memory: true
          report: compilation-report-app.xml

      - name: Build WxDatDecryptTool with Nuitka
        uses: Nuitka/Nuitka-Action@v1.4
        with:
          script-name: tool.py
          mode: onefile
          output-dir: dist
          output-file: WxDatDecryptTool.exe
          windows-icon-from-ico: frontend/static/icons/tool.ico
          disable-cache: false
          assume-yes-for-downloads: true

          lto: yes
          jobs: -1

          noinclude-setuptools-mode: error
          noinclude-pytest-mode: error
          noinclude-unittest-mode: nofollow
          noinclude-pydoc-mode: error
          noinclude-IPython-mode: error

          python-flag: no_docstrings,no_asserts

          show-memory: true
          report: compilation-report-tool.xml

      - name: Collect executables
        run: |
          mkdir artifacts
          copy dist\WxDatDecryptApp.exe artifacts\
          copy dist\WxDatDecryptTool.exe artifacts\

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WxDatDecrypt-windows
          path: artifacts\*

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/WxDatDecryptApp.exe
            artifacts/WxDatDecryptTool.exe
          draft: false
          prerelease: false
          generate_release_notes: true
