name: Python application

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync

      - name: Build executables with PyInstaller
        run: |
          uv run --with pyinstaller pyinstaller app.py `
            --noconfirm --onefile --name WxDatDecryptApp `
            --add-data "frontend/templates;frontend/templates" `
            --add-data "frontend/static;frontend/static" `
            --add-binary "backend/src/wxam/VoipEngine.dll" `
            --icon "frontend/static/icons/app.ico"

          uv run --with pyinstaller pyinstaller tool.py `
            --noconfirm --onefile --name WxDatDecryptTool `
            --icon "frontend/static/icons/tool.ico"

      - name: Collect executables
        run: |
          mkdir artifacts
          copy dist\WxDatDecryptApp.exe artifacts\
          copy dist\WxDatDecryptTool.exe artifacts\

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WxDatDecrypt-windows
          path: artifacts\*

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/WxDatDecryptApp.exe
            artifacts/WxDatDecryptTool.exe
          draft: false
          prerelease: false
          generate_release_notes: true
